proc format lib=work;
value wojfmt
2= 'DOLNOŒL¥SKIE'
4= 'KUJAWSKO-POMORSKIE'
6= 'LUBELSKIE'
8= 'LUBUSKIE'
10= '£ÓDZKIE'
12= 'MA£OPOLSKIE'
14= 'MAZOWIECKIE'
16= 'OPOLSKIE'
18= 'PODKARPACKIE'
20= 'PODLASKIE'
22= 'POMORSKIE'
24= 'ŒL¥SKIE'
26= 'ŒWIÊTOKRZYSKIE'
28= 'WARMIÑSKO-MAZURSKIE'
30= 'WIELKOPOLSKIE'
32= 'ZACHODNIOPOMORSKIE'
;
run;